services:
  br.seumanoel.empacotamento.api:
    image: ${DOCKER_REGISTRY-}brseumanoelempacotamentoapi
    build:
      context: .
      dockerfile: br.seumanoel.empacotamento.api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
    env_file:
      - .env
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"  # HTTP port map to 5000
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenhaSuperForte123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  sqlserver_data: